name: gbd
channels:
  - defaults
dependencies:
  - python=3.8  # Specifying Python version, adjust as needed
  - pyodbc
  - pandas
  - numpy
  - sqlalchemy
  - jupyter
  - pip
  - psycopg2
  - openpyxl
  - pyarrow
  - fastparquet
  - pip:
      - pprint
